## An analysis report
From the data web:
Detailed Accuracy
Correctly Classified Instances 	164662 	99.4144 %
Incorrectly Classified Instances 	970 	0.5856 %
Root mean squared error 	0.0463 	
Relative absolute error 	0.7938 % 	
Relative absolute error 	0.7938 % 	

Detailed Accuracy by Class
TP Rate 	FP Rate 	Precision 	Recall 	F-Measure 	ROC Area 	Class
0.999 	0 	1 	0.999 	0.999 	1 	Sitting
0.971 	0.002 	0.969 	0.971 	0.970 	0.999 	Sitting down
0.999 	0.001 	0.998 	0.999 	0.999 	1 	Standing
0.962 	0.003 	0.969 	0.962 	0.965 	0.999 	Standing up
0.998 	0.001 	0.998 	0.998 	0.998 	1 	Walking
0.994 	0.001 	0.994 	0.994 	0.994 	1 	Weighted Avg.

We use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.(Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013.)

They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. Given data from accelerometers, the goal is to predict the class of action which is one of the following.

A.Exactly according to the specification
B. Throwing elbows to the front 
C. Lifting the dumbbell only halfway 
D. Lowering the dumbbell only halfway 
E. Throwing the hips to the front



Some Data Infoamation:

The training data for this project are available here:
https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here:
https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://web.archive.org/web/20161224072740/http:/groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.(From the website.)



The code is as follow:

##To begin with.
library(RCurl)
train_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
test_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
train_data <- read.csv(text=getURL(train_url), na.strings=c("", "NA"))
test_data <- read.csv(text=getURL(test_url), na.strings=c("", "NA"))
train_data$X <- NULL

cols_to_remove <- c("user_name", "raw_timestamp_part_1",
    "raw_timestamp_part_2", "cvtd_timestamp")
for (col in cols_to_remove) {
   train_data[, col] <- NULL
}

NAs <- apply(train_data,2,function(x) {sum(is.na(x))})
train_data <- train_data[,which(NAs == 0)]

library(caret)
nsv <- nearZeroVar(train_data)
train_data <- train_data[-nsv]
test_data <- test_data[-nsv]

names(train_data)


## To measure the mode’s accuracy l, a 10-fold cross validation can be done with 80:20 split. On each fold, the 80% of data is used for training the random forest and 20% is for test.

library(randomForest)
set.seed(1)
obs <- c()
preds <- c()
for(i in 1:10) {
   intrain = sample(1:dim(train_data)[1], size=dim(train_data)[1] * 0.8, replace=F)
   train_cross = train_data[intrain,]
   test_cross = train_data[-intrain,]
   rf <- randomForest(classe ~ ., data=train_cross)
   obs <- c(obs, test_cross$classe)
   preds <- c(preds, predict(rf, test_cross))
}

conf_mat <- confusionMatrix(table(preds, obs))
conf_mat$table

model <- randomForest(classe ~ ., data=train_data)
